import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Underline from "@tiptap/extension-underline";
import "./SummaryPage.css";

function SummaryPage() {
  const navigate = useNavigate();
  const [summary, setSummary] = useState(
    "<p>Summarization generated by the LLM will appear here. " +
      "The 'Save' button exports the generated summary into a word document. " +
      "This text editor is editable and has the ability to support Bolding, Underlines, Italics, and Jot Notes. " +
      "The 'Return' button returns to the transcription page. </p>"
  );

  const handleReturn = () => navigate("/");
  const handleSave = () => alert("Save to Word document functionality coming soon!");

  // dummy state to force rerenders for toolbar active states
  const [, setTick] = useState(0);

  const editor = useEditor({
    extensions: [StarterKit, Underline],
    content: summary,
    onUpdate: ({ editor }) => setSummary(editor.getHTML()),
  });

  // Force a React re-render whenever the editor state changes
  useEffect(() => {
    if (!editor) return;

    const rerender = () => setTick((t) => t + 1);

    editor.on("transaction", rerender);
    editor.on("selectionUpdate", rerender);
    editor.on("update", rerender);

    return () => {
      editor.off("transaction", rerender);
      editor.off("selectionUpdate", rerender);
      editor.off("update", rerender);
    };
  }, [editor]);

  if (!editor) return null;

  return (
    <div className="summary-container">
      {/* Toolbar row */}
      <div className="toolbar-row">
        <div className="toolbar">
          <button
            onClick={() => editor.chain().focus().toggleBold().run()}
            className={editor.isActive("bold") ? "active" : ""}
            aria-label="Bold"
          >
            <b>B</b>
          </button>
          <button
            onClick={() => editor.chain().focus().toggleItalic().run()}
            className={editor.isActive("italic") ? "active" : ""}
            aria-label="Italic"
          >
            <i>I</i>
          </button>
          <button
            onClick={() => editor.chain().focus().toggleUnderline().run()}
            className={editor.isActive("underline") ? "active" : ""}
            aria-label="Underline"
          >
            <u>U</u>
          </button>
          <button
            onClick={() => editor.chain().focus().toggleBulletList().run()}
            className={editor.isActive("bulletList") ? "active" : ""}
            aria-label="Bulleted list"
          >
            ••
          </button>
        </div>

        {/* Save button on top right */}
        <button className="save-button-top" onClick={handleSave}>
          SAVE
        </button>
      </div>

      {/* Main editor */}
      <div className="editor-wrapper">
        <EditorContent editor={editor} className="summary-editor" />
      </div>

      {/* Return button full width */}
      <div className="return-button-container">
        <button className="return-button" onClick={handleReturn}>
          RETURN
        </button>
      </div>
    </div>
  );
}

export default SummaryPage;








